// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysticForge.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MysticForge.Infrastructure.Migrations
{
    [DbContext(typeof(MysticForgeDbContext))]
    [Migration("20260423001833_AddCardsAndIngestTables")]
    partial class AddCardsAndIngestTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MysticForge.Domain.Cards.Card", b =>
                {
                    b.Property<Guid>("OracleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<decimal?>("Cmc")
                        .HasColumnType("numeric")
                        .HasColumnName("cmc");

                    b.PrimitiveCollection<string[]>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("color_identity");

                    b.PrimitiveCollection<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<string>("Faces")
                        .HasColumnType("jsonb")
                        .HasColumnName("card_faces");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<DateTimeOffset>("LastOracleChange")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_oracle_change");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("OracleHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("oracle_hash");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<string>("TypeLine")
                        .HasColumnType("text")
                        .HasColumnName("type_line");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OracleId")
                        .HasName("pk_cards");

                    b.HasIndex("ColorIdentity")
                        .HasDatabaseName("cards_color_identity_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ColorIdentity"), "gin");

                    b.HasIndex("Keywords")
                        .HasDatabaseName("cards_keywords_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Keywords"), "gin");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("cards_face_shape_chk", "(oracle_text IS NOT NULL AND type_line IS NOT NULL AND card_faces IS NULL) OR (oracle_text IS NULL AND type_line IS NULL AND card_faces IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Cards.Printing", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collector_number");

                    b.Property<string>("ImageUriNormal")
                        .HasColumnType("text")
                        .HasColumnName("image_uri_normal");

                    b.Property<string>("ImageUriSmall")
                        .HasColumnType("text")
                        .HasColumnName("image_uri_small");

                    b.Property<DateTimeOffset>("LastPriceUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_price_update");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price_eur");

                    b.Property<decimal?>("PriceEurFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("price_eur_foil");

                    b.Property<decimal?>("PriceTix")
                        .HasColumnType("numeric")
                        .HasColumnName("price_tix");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<decimal?>("PriceUsdEtched")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd_etched");

                    b.Property<decimal?>("PriceUsdFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd_foil");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date")
                        .HasColumnName("released_at");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("text")
                        .HasColumnName("scryfall_uri");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_code");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ScryfallId")
                        .HasName("pk_printings");

                    b.HasIndex("OracleId")
                        .HasDatabaseName("printings_oracle_id_idx");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("printings_set_code_idx");

                    b.ToTable("printings", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Events.CardOracleEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<byte[]>("NewHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("new_hash");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<byte[]>("PreviousHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_hash");

                    b.HasKey("EventId")
                        .HasName("pk_card_oracle_events");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("card_oracle_events_unconsumed_idx")
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("OracleId")
                        .HasDatabaseName("ix_card_oracle_events_oracle_id");

                    b.ToTable("card_oracle_events", (string)null);
                });

            modelBuilder.Entity("MysticForge.Infrastructure.Persistence.Entities.ScryfallIngestRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RunId"));

                    b.Property<string>("BulkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bulk_type");

                    b.Property<int?>("CardsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("cards_inserted");

                    b.Property<int?>("CardsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("cards_updated");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ErrataEmitted")
                        .HasColumnType("integer")
                        .HasColumnName("errata_emitted");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int?>("PrintingsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("printings_inserted");

                    b.Property<int?>("PrintingsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("printings_updated");

                    b.Property<DateTimeOffset>("ScryfallUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scryfall_updated_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.HasKey("RunId")
                        .HasName("pk_scryfall_ingest_runs");

                    b.ToTable("scryfall_ingest_runs", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Cards.Printing", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_printings_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Events.CardOracleEvent", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_oracle_events_cards_oracle_id");
                });
#pragma warning restore 612, 618
        }
    }
}
