// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysticForge.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MysticForge.Infrastructure.Migrations
{
    [DbContext(typeof(MysticForgeDbContext))]
    [Migration("20260426233308_AddTaggingPipeline")]
    partial class AddTaggingPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MysticForge.Domain.Cards.Card", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<decimal?>("Cmc")
                        .HasColumnType("numeric")
                        .HasColumnName("cmc");

                    b.PrimitiveCollection<string[]>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("color_identity");

                    b.PrimitiveCollection<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<string>("Faces")
                        .HasColumnType("jsonb")
                        .HasColumnName("card_faces");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<DateTimeOffset>("LastOracleChange")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_oracle_change");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("OracleHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("oracle_hash");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<string>("TypeLine")
                        .HasColumnType("text")
                        .HasColumnName("type_line");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OracleId")
                        .HasName("pk_cards");

                    b.HasIndex("ColorIdentity")
                        .HasDatabaseName("cards_color_identity_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ColorIdentity"), "gin");

                    b.HasIndex("Keywords")
                        .HasDatabaseName("cards_keywords_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Keywords"), "gin");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("cards_face_shape_chk", "(oracle_text IS NOT NULL AND type_line IS NOT NULL AND card_faces IS NULL) OR (oracle_text IS NULL AND type_line IS NULL AND card_faces IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Cards.Printing", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collector_number");

                    b.Property<string>("ImageUriNormal")
                        .HasColumnType("text")
                        .HasColumnName("image_uri_normal");

                    b.Property<string>("ImageUriSmall")
                        .HasColumnType("text")
                        .HasColumnName("image_uri_small");

                    b.Property<DateTimeOffset>("LastPriceUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_price_update");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price_eur");

                    b.Property<decimal?>("PriceEurFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("price_eur_foil");

                    b.Property<decimal?>("PriceTix")
                        .HasColumnType("numeric")
                        .HasColumnName("price_tix");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<decimal?>("PriceUsdEtched")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd_etched");

                    b.Property<decimal?>("PriceUsdFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd_foil");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<DateOnly?>("ReleasedAt")
                        .HasColumnType("date")
                        .HasColumnName("released_at");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("text")
                        .HasColumnName("scryfall_uri");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_code");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ScryfallId")
                        .HasName("pk_printings");

                    b.HasIndex("OracleId")
                        .HasDatabaseName("printings_oracle_id_idx");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("printings_set_code_idx");

                    b.ToTable("printings", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Events.CardOracleEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<short>("ClaimAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("claim_attempts");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<byte[]>("NewHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("new_hash");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<byte[]>("PreviousHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_hash");

                    b.HasKey("EventId")
                        .HasName("pk_card_oracle_events");

                    b.HasIndex("ClaimedAt")
                        .HasDatabaseName("card_oracle_events_claim_idx")
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("card_oracle_events_unconsumed_idx")
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("OracleId")
                        .HasDatabaseName("ix_card_oracle_events_oracle_id");

                    b.ToTable("card_oracle_events", null, t =>
                        {
                            t.HasCheckConstraint("card_oracle_events_event_type_chk", "event_type IN ('created', 'errata', 'model_bump', 'taxonomy_bump')");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardMechanic", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<long>("MechanicId")
                        .HasColumnType("bigint")
                        .HasColumnName("mechanic_id");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("TaggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tagged_at");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("OracleId", "MechanicId")
                        .HasName("pk_card_mechanics");

                    b.HasIndex("MechanicId")
                        .HasDatabaseName("ix_card_mechanics_mechanic_id");

                    b.ToTable("card_mechanics", null, t =>
                        {
                            t.HasCheckConstraint("card_mechanics_source_chk", "source IN ('llm', 'human')");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardRole", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("TaggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tagged_at");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("OracleId", "Role")
                        .HasName("pk_card_roles");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_card_roles_role");

                    b.ToTable("card_roles", null, t =>
                        {
                            t.HasCheckConstraint("card_roles_source_chk", "source IN ('llm', 'human')");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardSynergyHook", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<long>("HookId")
                        .HasColumnType("bigint")
                        .HasColumnName("hook_id");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("TaggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tagged_at");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("OracleId", "HookId")
                        .HasName("pk_card_synergy_hooks");

                    b.HasIndex("HookId")
                        .HasDatabaseName("ix_card_synergy_hooks_hook_id");

                    b.ToTable("card_synergy_hooks", null, t =>
                        {
                            t.HasCheckConstraint("card_synergy_hooks_source_chk", "source IN ('llm', 'human')");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardSynergyHookAncestor", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<long>("AncestorHookId")
                        .HasColumnType("bigint")
                        .HasColumnName("ancestor_hook_id");

                    b.HasKey("OracleId", "AncestorHookId")
                        .HasName("pk_card_synergy_hook_ancestors");

                    b.HasIndex("AncestorHookId")
                        .HasDatabaseName("ix_card_synergy_hook_ancestors_ancestor_hook_id");

                    b.ToTable("card_synergy_hook_ancestors", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardTribalInterest", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<string>("CreatureType")
                        .HasColumnType("text")
                        .HasColumnName("creature_type");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("TaggedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("tagged_at");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("OracleId", "CreatureType")
                        .HasName("pk_card_tribal_interest");

                    b.HasIndex("CreatureType")
                        .HasDatabaseName("ix_card_tribal_interest_creature_type");

                    b.ToTable("card_tribal_interest", null, t =>
                        {
                            t.HasCheckConstraint("card_tribal_interest_source_chk", "source IN ('llm', 'human')");
                        });
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.Mechanic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reviewed");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.HasKey("Id")
                        .HasName("pk_mechanics");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mechanics_name");

                    b.HasIndex("Reviewed")
                        .HasDatabaseName("mechanics_reviewed_false_idx")
                        .HasFilter("reviewed = false");

                    b.ToTable("mechanics", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.SynergyHook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Depth")
                        .HasColumnType("smallint")
                        .HasColumnName("depth");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_synergy_hooks");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_synergy_hooks_parent_id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_synergy_hooks_path");

                    b.ToTable("synergy_hooks", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.TagFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<string>("ErrorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_kind");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("FailedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("failed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_version");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.HasKey("Id")
                        .HasName("pk_tag_failures");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_tag_failures_event_id");

                    b.HasIndex("FailedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_tag_failures_failed_at");

                    b.HasIndex("OracleId")
                        .HasDatabaseName("ix_tag_failures_oracle_id");

                    b.ToTable("tag_failures", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.TaxonomyMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SeededAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("seeded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TaxonomyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("Id")
                        .HasName("pk_taxonomy_metadata");

                    b.ToTable("taxonomy_metadata", null, t =>
                        {
                            t.HasCheckConstraint("taxonomy_metadata_singleton_chk", "id = 1");
                        });
                });

            modelBuilder.Entity("MysticForge.Infrastructure.Persistence.Entities.ScryfallIngestRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RunId"));

                    b.Property<string>("BulkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bulk_type");

                    b.Property<int?>("CardsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("cards_inserted");

                    b.Property<int?>("CardsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("cards_updated");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ErrataEmitted")
                        .HasColumnType("integer")
                        .HasColumnName("errata_emitted");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int?>("PrintingsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("printings_inserted");

                    b.Property<int?>("PrintingsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("printings_updated");

                    b.Property<DateTimeOffset>("ScryfallUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scryfall_updated_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.HasKey("RunId")
                        .HasName("pk_scryfall_ingest_runs");

                    b.ToTable("scryfall_ingest_runs", (string)null);
                });

            modelBuilder.Entity("MysticForge.Domain.Cards.Printing", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_printings_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Events.CardOracleEvent", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_oracle_events_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardMechanic", b =>
                {
                    b.HasOne("MysticForge.Domain.Tags.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_mechanics_mechanics_mechanic_id");

                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_mechanics_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardRole", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_roles_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardSynergyHook", b =>
                {
                    b.HasOne("MysticForge.Domain.Tags.SynergyHook", null)
                        .WithMany()
                        .HasForeignKey("HookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_synergy_hooks_synergy_hooks_hook_id");

                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_synergy_hooks_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardSynergyHookAncestor", b =>
                {
                    b.HasOne("MysticForge.Domain.Tags.SynergyHook", null)
                        .WithMany()
                        .HasForeignKey("AncestorHookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_synergy_hook_ancestors_synergy_hooks_ancestor_hook_id");

                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_synergy_hook_ancestors_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.CardTribalInterest", b =>
                {
                    b.HasOne("MysticForge.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_tribal_interest_cards_oracle_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.SynergyHook", b =>
                {
                    b.HasOne("MysticForge.Domain.Tags.SynergyHook", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_synergy_hooks_synergy_hooks_parent_id");
                });

            modelBuilder.Entity("MysticForge.Domain.Tags.TagFailure", b =>
                {
                    b.HasOne("MysticForge.Domain.Events.CardOracleEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_failures_card_oracle_events_event_id");
                });
#pragma warning restore 612, 618
        }
    }
}
